export const AppActionTypes = {
    TOGGLE_THEME: 'TOGGLE_THEME',
};

export const CountriesActionTypes  = {
    SET_LOADING: 'SET_LOADING',
    GET_COUNTRIES: 'GET_COUNTRIES',
    FILTER_COUNTRIES: 'FILTER_COUNTRIES',
    SEARCH_COUNTRIES: 'SEARCH_COUNTRIES',
    CLEAR_SEARCH_COUNTRIES: 'CLEAR_SEARCH_COUNTRIES',
    GET_COUNTRY: 'GET_COUNTRY',
    COUNTRY_ERROR: 'COUNTRY_ERROR',
}

